Move pull request for domain whitelisting feature.
Cretezy/pymessenger2 pull request #10
Opened 2017-03-23 09:34 UTC by karlinnolabs

2017-03-23 14:03 UTC, Cretezy commented
Remove all the `(object)` and I'll accept. :+1:

2017-03-23 14:05 UTC, karlinnolabs commented
the (object) is required because you're using @attr decorators which when trying to run this code with Python2 causes the following error "attrs only works with new-style classes".

Using the object subclass doesn't change things in python3 but makes this code work in python2.

2017-03-23 18:51 UTC, Cretezy commented
We aren't actively supporting Python 2. Is there a reason you are still using Python 3?

2017-03-23 19:24 UTC, karlinnolabs commented
Not all of the libraries in my project are python 3 yet, I'll be spending some time cleaning that up in a few months time but until then I'm stuck on python 2.

2017-03-23 19:25 UTC, Cretezy commented
I know @sils wanted to work towards a Python 3-only library, but if it's only a few lines addition, I don't see the harm into supporting both.

2017-03-23 19:31 UTC, karlinnolabs commented
thanks, python3 isn't 100% yet, but soon ;)

2017-03-24 07:24 UTC, sils requested changes
Ideally I'd squash the commits in the following manner:

- do a `rebase -i` that should get rid of that merge conflict
- squash the first two commits so we don't have `oops` commits in the history
- keep the last one

I'd advise to shorten the commit message shortlogs to make them better skimmable.

Note that the ultimate decision on this is on @Cretezy and I'm only giving an external recommendation as another contributor of the library.

2017-03-24 07:24 UTC, sils commented on pymessenger2/bot.py
> +    def add_domains_to_whitelist(self, domains):
I'd name it `whitelist_domains` FWIW

2017-03-24 07:24 UTC, sils commented on pymessenger2/bot.py
> +        return result
any reason you can't use `send_raw`?

2017-05-08 23:44 UTC, merged

2017-05-08 23:45 UTC, Cretezy commented
Merged it. Doesn't hurt to passively support some Python 2.